blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from django.urls import reverse_lazy
from.views import signup, log_in, log_out

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url='users/password_reset/done/'),
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url='/users/reset/done/'),
        name='password_reset_complete'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["username"]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email')

class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField()

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.urls import reverse

from .forms import SignUpForm, LoginForm

def signup(request):
    if request.user.is_authenticated:
        return redirect('core:home')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Welcome to SOBER AF!")
            return redirect('core:home')
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})

def log_in(request):
    if request.user.is_authenticated:
        return redirect('core:home')
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect('core:home')
            else:
                messages.error(request, 'Invalid email or password')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})

def log_out(request):
    logout(request)
    return redirect(reverse('users:login'))

templates/users/login.html
{% extends 'base.html' %}

{% block head_title %}Log In{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class=" my-5">Log in</h2>
      <form method="post">
        {% csrf_token %}

        <div class="form-group">
          {{ form.email.label_tag }}
          <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
            name="email" value='{{ form.email.value|default:"" }}'>
          {% if form.email.errors %}
          <div class="invalid-feedback">{{ form.email.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password.label_tag }}
          <input type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}"
            id="id_password" name="password" value='{{ form.password.value|default:"" }}'>
          {% if form.password.errors %}
          <div class="invalid-feedback">{{ form.password.errors }}</div>
          {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Sign up</button>
      </form>
      <br>
      <p>Forgot your password? <a href="{% url 'users:password_reset' %}">Reset it.</a></p>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset.html
{% extends 'base.html' %}

{% block head_title %}Password Reset{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-4">
      <h2 class=" my-5">Password Reset</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.email.label_tag }}
          <input type="email" class="form-control" id="id_email" name="email" value='{{ form.email.value|default:"" }}'>
        </div>
        <button type="submit" class="btn btn-primary">Reset Password</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block head_title %}Successful Password Change{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="my-5">Successful Password Change</h2>
      <p>
        Password change successful. <a href="{% url 'users:login' %}">Log in.</a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block head_title %}New Password{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class=" my-5">Change Password</h2>
      {% if validlink %}
      <div class="row">
        <form class="col-4" method="post">
          {% csrf_token %}
          <div class="form-group">
            {{ form.new_password1.label_tag }}
            <input type="password" class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
              id="id_new_password1" name="new_password1" value='{{ form.new_password1.value|default:"" }}'>
            {% if form.new_password1.errors %}
            <div class="invalid-feedback">{{ form.new_password1.errors }}</div>
            {% endif %}
          </div>

          <div class="form-group">
            {{ form.new_password2.label_tag }}
            <input type="password" class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
              id="id_new_password2" name="new_password2" value='{{ form.new_password2.value|default:"" }}'>
            {% if form.new_password2.errors %}
            <div class="invalid-feedback">{{ form.new_password2.errors }}</div>
            {% endif %}
          </div>
          <button type="submit" class="btn btn-primary">Change Password</button>
        </form>
      </div>
      {% else %}
      <p>
        Invalid link. Request a new <a href="{% url 'users:password_reset' %}">link.</a>
      </p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block head_title %}Reset Password{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class=" col-12">
      <h2 class="my-5">Password Reset</h2>
      <p>
        Instructions for resetting your password have been sent to the email on file. If you have an account with the email you entered, you should receive them shortly.
      </p>
      <p>
        If you haven't received an email, make sure you've entered the correct email and check your spam folder.
      </p>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset_email.html
To reset the password for {{ user.username }} click the link below:
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

If the above link does not work copy and paste the URL into a new window.

templates/users/signup.html
{% extends 'base.html' %}

{% block head_title %}Sign Up{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="my-5">Sign up For an Account</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.username.label_tag }}
          <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
            name="username" value='{{ form.username.value|default:"" }}'>
          <small class="text-muted">{{ form.username.help_text }}</small>
          {% if form.username.errors %}
          <div class="invalid-feedback">{{ form.username.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.email.label_tag }}
          <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
            name="email" value='{{ form.email.value|default:"" }}'>
          {% if form.email.errors %}
          <div class="invalid-feedback">{{ form.email.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password1.label_tag }}
          <input type="password" class="form-control {% if form.password1.errors %}is-invalid{% endif %}"
            id="id_password1" name="password1" value='{{ form.password1.value|default:"" }}'>
          <small class="text-muted">{{ form.password1.help_text }}</small>
          {% if form.password1.errors %}
          <div class="invalid-feedback">{{ form.password1.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password2.label_tag }}
          <input type="password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}"
            id="id_password2" name="password2" value='{{ form.password2.value|default:"" }}'>
          <small class="text-muted">{{ form.password2.help_text }}</small>
          {% if form.password2.errors %}
          <div class="invalid-feedback">{{ form.password2.errors }}</div>
          {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Sign up</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}